apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /(/|$)(.*)
        backend:
          service:
            name: py-web
            port:
              number: 8080
      - pathType: ImplementationSpecific
        path: /py
        backend:
          service:
            name: py-web
            port:
              number: 8080
      - pathType: ImplementationSpecific
        path: /go
        backend:
          service:
            name: go-web
            port:
              number: 8080
